apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: one
          image: ganesh6498/deploy3
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ser
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 80

